/* @pjs pauseOnBlur="true"; 
        preload="AskCore.png,
                 AskNum.png,
                 AskRoller.png,
                 Autoknit.png,
                 ChooseColor.png,
                 ColorCard.png,
                 CoreText.png,
                 FirstError.png,
                 LastColor.png,
                 LengthError.png,
                 Neighbor.png,
                 Output.png,
                 OutputSuccess.png,
                 Reknit.png,
                 Restart.png,
                 Reuse.png,
                 RollerText.png,
                 Skewknit.png,
                 Start.png,
                 Undo.png,
                 UndoSuccess.png,
                 Vknit.png"; */

